"""empty message

Revision ID: 36862dadf42b
Revises: 2807edd385a2
Create Date: 2021-10-28 09:45:34.133430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36862dadf42b'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_url', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_url')
    # ### end Alembic commands ###
